"""change entity mapping to spring boot

Revision ID: 414bb88b2cbd
Revises: 36361dbca679
Create Date: 2025-06-17 21:37:13.151102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '414bb88b2cbd'
down_revision: Union[str, Sequence[str], None] = '36361dbca679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kafka_message', sa.Column('player_id', sa.Integer(), nullable=True))
    op.add_column('kafka_message', sa.Column('round_id', sa.Integer(), nullable=True))
    op.alter_column('kafka_message', 'score_value',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="score_value::boolean"
                    )
    op.drop_column('kafka_message', 'match_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kafka_message', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('kafka_message', 'score_value',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('kafka_message', 'round_id')
    op.drop_column('kafka_message', 'player_id')
    # ### end Alembic commands ###
