"""change round_id to game_set_id

Revision ID: 86a2ec4a46ee
Revises: 414bb88b2cbd
Create Date: 2025-06-18 23:03:22.739303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a2ec4a46ee'
down_revision: Union[str, Sequence[str], None] = '414bb88b2cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kafka_message', sa.Column('game_set_id', sa.Integer(), nullable=True))
    op.drop_column('kafka_message', 'round_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kafka_message', sa.Column('round_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('kafka_message', 'game_set_id')
    # ### end Alembic commands ###
