"""create kafka msg tables

Revision ID: f7b08d1c00dc
Revises: 
Create Date: 2025-06-17 17:49:43.413360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b08d1c00dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kafka_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('cue_ball_id', sa.Integer(), nullable=True),
    sa.Column('score_value', sa.Integer(), nullable=True),
    sa.Column('is_foul', sa.Boolean(), nullable=True),
    sa.Column('is_uncertain', sa.Boolean(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('scene_url', sa.String(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kafka_message_id'), 'kafka_message', ['id'], unique=False)
    op.create_table('ball',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_x', sa.Integer(), nullable=True),
    sa.Column('start_y', sa.Integer(), nullable=True),
    sa.Column('end_x', sa.Integer(), nullable=True),
    sa.Column('end_y', sa.Integer(), nullable=True),
    sa.Column('potted', sa.Boolean(), nullable=True),
    sa.Column('kafka_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kafka_message_id'], ['kafka_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ball_id'), 'ball', ['id'], unique=False)
    op.create_table('collision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ball1', sa.Integer(), nullable=True),
    sa.Column('ball2', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('kafka_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kafka_message_id'], ['kafka_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collision_id'), 'collision', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collision_id'), table_name='collision')
    op.drop_table('collision')
    op.drop_index(op.f('ix_ball_id'), table_name='ball')
    op.drop_table('ball')
    op.drop_index(op.f('ix_kafka_message_id'), table_name='kafka_message')
    op.drop_table('kafka_message')
    # ### end Alembic commands ###
