from enum import Enum

class ErrorCode(str ,Enum):
    INVALID_INPUT = "INVALID_INPUT"
    DATABASE_INSERT_ERROR = "DATABASE_INSERT_ERROR"
    DATABASE_COMMIT_ERROR = "DATABASE_COMMIT_ERROR"
    KAFKA_ERROR = "KAFKA_ERROR"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
    MESSAGE_LIST_NOT_FOUND = "MESSAGE_LIST_NOT_FOUND"
    DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR"
    DATABASE_DELETE_ERROR = "DATABASE_DELETE_ERROR"
    JSON_DECODE_ERROR = "JSON_DECODE_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    S3_UPLOAD_FAILED = "S3_UPLOAD_FAILED"
    S3_LIST_FAILED = "S3_LIST_FAILED"
    S3_DELETE_FAILED = "S3_DELETE_FAILED"
    KAFKA_SEND_FAILED = "KAFKA_SEND_FAILED"

